### ISSUE TITLE
Constructors with arguments are not accepted by (new () => T) signature

### ISSUE THREAD

**Issue by buchatsky** [umutozel/Beetle.js#6]
When a custom entity class is derived from EntityBase class whose constructor takes 3 arguments
```
export class CustomEntity extends EntityBase {
...
}
```
the typescript complains at code 
`let query: querying.EntityQuery<CustomEntity> = this.em.createQuery<CustomEntity>('CustomEntities', CustomEntity);`
with an error:

> TS2345	(TS) Argument of type 'typeof CustomEntity' is not assignable to parameter of type 'string | (new () => CustomEntity)'.
>   Type 'typeof CustomEntity' is not assignable to type 'new () => CustomEntity'.

The createQuery construct signature should be "(new (...args: any[]) => T)" instead of "(new () => T)", as [suggested here](https://github.com/Microsoft/TypeScript/issues/2794#issuecomment-93713987) 

**Versions:**
beetle.js: 3.0.6
typescript: 3.5.3

**Comment by umutozel** [comment]
Fixed with 3.0.7. Thanks again for reporting and sorry for the delay.
